version: 2.1

jobs:
  say-hello1:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo 1"
  say-hello2:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo 2"
  say-hello3:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo 3"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello1:
      - say-hello2:
      - say-hello3:
          filters:
            branches:
              only: master
            tags:
              only: /^stg-\d{4}\d{2}\d{2}.*/
      - say-hello3:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^prod-\d{4}\d{2}\d{2}.*/